---
title: "Chapter 16 Homework"
subtitle: "Ch. 16: 8, 11, 13, 21, 25, 36"
author: "L E Delaney"
output:
  pdf_document:
      template: input/template.tex
      keep_tex: false 
      latex_engine: xelatex
  html_document:
    highlight: tango
    theme: cosmo
    toc: true
    toc_float: true
documentclass: "article"
fontsize: 11pt
geometry_options: margin = 1in
linestretch: 1
---
```{r setup, echo=FALSE, eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, out.extra = "")
library(tidyverse)

myoutput <- "latex"
#myoutput <- "html"

#For alpha lists
alpha.list <- function(optnum = 3, opta, optb, optc, optd, output = myoutput){
  
  if(output == "html"){
    if(optnum == 3){
   a <- paste("<ol type='a'>", 
       "\n", 
       "<li>",opta,"</li>", 
       "\n", 
       "<li>",optb,"</li>", 
       "\n", 
       "<li>",optc,"</li>", 
       "\n","</ol>", sep = " ") %>%
     noquote()}
    else if(optnum == 2){
         a <- paste("<ol type='a'>", 
       "\n", 
       "<li>",opta,"</li>", 
       "\n", 
       "<li>",optb,"</li>", 
       "\n","</ol>", sep = " ") %>%
     noquote()
      
    }
    
     else if(optnum == 4){
        a <- paste("<ol type='a'>", 
       "\n", 
       "<li>",opta,"</li>", 
       "\n", 
       "<li>",optb,"</li>", 
       "\n", 
       "<li>",optc,"</li>",
       "\n", 
       "<li>",optd,"</li>",
       "\n","</ol>", sep = " ") %>%
             
     noquote()
      
    }
   
   return(a)
    
  }
  
  else if(output == "latex"){
    if(optnum == 3){
    b <- paste("\\begin{enumerate}", 
       "\n", 
       "\\item[a.]{",opta,"}", 
       "\n", 
       "\\item[b.]{",optb,"}", 
       "\n", 
       "\\item[c.]{",optc,"}", 
       "\n","\\end{enumerate}", sep = " ") %>%
      noquote()}
    else if(optnum == 2){
      b <- paste("\\begin{enumerate}", 
       "\n", 
       "\\item[a.]{",opta,"}", 
       "\n", 
       "\\item[b.]{",optb,"}", 
       "\n","\\end{enumerate}", sep = " ") %>%
      noquote()
      
    }
    
    else if(optnum == 4){
    b <- paste("\\begin{enumerate}", 
       "\n", 
       "\\item[a.]{",opta,"}", 
       "\n", 
       "\\item[b.]{",optb,"}", 
       "\n", 
       "\\item[c.]{",optc,"}", 
       "\n", 
       "\\item[d.]{",optd,"}", 
       "\n","\\end{enumerate}", sep = " ") %>%
      noquote()}
    
    return(b)
  }
  
}

latex.only <- function(mytext, output = myoutput){
  
  if(output == "html"){
    return(NULL)
  }
  
  else if(output == "latex"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output == "word"){
    return(NULL)
    
  }
}

html.only <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    return(NULL)
  }
  
  else if(output == "html"){
    b <- paste0(mytext) %>%
      noquote()
    return(b)
  }
  
  else if(output == "word"){
    return(NULL)
    
  }
}


bold.fix <- function(mytext, output = myoutput){
  
  if(output == "latex"){
    a <- paste0("\\textbf{", mytext, "}") %>%
      noquote()
    
    return(a)
  }
  
  else if(output == "html"){
    b <- paste0("<strong>", mytext, "</strong>") %>%
      noquote()
    return(b)
  }
  
  else if(output == "word"){
    return(mytext)
    
  }
}


```

:::: {.blackbox data-latex=""}

8. Consider the following wild-type and mutant sequences:


:::: {.center data-latex=""}

Wild-type ....CTTGCAAGCGAATC.... 

Mutant ....CTTGCTAGCGAATC....

::::

The substitution shown seems to have created a stop codon. What further information do you need
to be confident that it has done so?

`r latex.only("\\vspace{17cm}")`

::::


:::: {.blackbox data-latex=""}

11. By base-pair substitution, what are all the synonymous changes that can be made starting with the codon CGG?


`r latex.only("\\vspace{19cm}")`

::::

:::: {.blackbox data-latex=""}

13. 
`r alpha.list(optnum = 2, opta = "Acridine orange is an effective mutagen for producing null alleles by mutation. Why does it produce null alleles?", optb = "A certain acridine-like compound generates only single insertions. A mutation induced with this compound is treated with the same compound, and some revertants are produced. How is this outcome possible?")`

`r latex.only("\\vspace{19cm}")`

::::

:::: {.blackbox data-latex=""}

21. Differentiate between the elements of the following pairs: 

a. Transitions and transversions

b. Synonymous and neutral mutations

c. Missense and nonsense mutations

d. Frameshift and nonsense mutations


`r latex.only("\\vspace{19cm}")`


::::

:::: {.blackbox data-latex=""}

25. A certain compound that is an analog of the base cytosine can become incorporated into DNA. It normally hydrogen bonds just as cytosine does, but it quite often isomerizes to a form that hydrogen bonds as thymine does. Do you expect this compound to be mutagenic, and, if so, what types of changes might it induce at the DNA level?


`r latex.only("\\vspace{20cm}")`

::::

:::: {.blackbox data-latex=""}

36. You are working with a newly discovered mutagen, and you wish to determine the base change that it introduces into DNA. Thus far, you have determined that the mutagen chemically alters a single base in such a way that its base-pairing properties are altered permanently. To determine the specificity of the alteration, you examine the amino acid changes that take place after mutagenesis. A sample of what you find is shown here:


:::: {.center data-latex=""}

Original: Gln–His–Ile–Glu–Lys

Mutant: Gln–His–Met–Glu–Lys

Original: Ala–Val–Asn–Arg

Mutant: Ala–Val–Ser–Arg

Original: Arg–Ser–Leu

Mutant:Arg–Ser–Leu–Trp–Lys–Thr–Phe 

::::

\

What is the base-change specificity of the mutagen?

`r latex.only("\\vspace{15cm}")`

::::

